// <auto-generated />
namespace TLO_KQGL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ALTER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ALTER));
        
        string IMigrationMetadata.Id
        {
            get { return "201801050543364_ALTER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
